<?php
	/**
	 * Archivo principal del módulo donde están los métodos generales
	 * como los son los hooks de drupal.
	 */

	/**
	 * hook_form_alter
	 *
	 * Modificar formularios acorde lo necesario para el módulo
	 *
	 * @param $form
	 * @param $form_state
	 * @param $form_id
	 */
	function eximia_form_alter(&$form, &$form_state, $form_id) {
		$options = array('' => '- Todos -');
		switch($form['#id']) {
			case 'contact-site-form':
				$form['name']['#title_display'] = 'invisible';
				$form['name']['#attributes'] = array('placeholder' => array(t('Name')));
				$form['mail']['#title_display'] = 'invisible';
				$form['mail']['#attributes'] = array('placeholder' => array(t('Email')));
				$form['subject']['#title_display'] = 'invisible';
				$form['message']['#title_display'] = 'invisible';
				//$form['copy']['#title_display'] = 'invisible';
				$form['actions']['submit']['#value'] = t('Send');
				break;
			default:
				$uno = 1;
				break;
		}
	}